/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.9.0.99.2 */
/* Module Version: 5.8 */
/* C:\lscc\diamond\3.9_x64\ispfpga\bin\nt64\scuba.exe -w -n DDR_TRANSMIT -lang verilog -synth lse -bus_exp 7 -bb -arch xo3c00f -type iol -mode out -io_type LVDS25 -width 1 -freq_in 64 -gear 1 -clk sclk -aligned -del -1  */
/* Fri Jun 02 13:37:24 2017 */


`timescale 1 ns / 1 ps
module DDR_TRANSMIT (clk, clkout, reset, sclk, dataout, dout)/* synthesis NGD_DRC_MASK=1 */;
    input wire clk;
    input wire reset;
    input wire [1:0] dataout;
    output wire clkout;
    output wire sclk;
    output wire [0:0] dout;

    wire db0;
    wire da0;
    wire buf_clkout;
    wire scuba_vlo;
    wire scuba_vhi;
    wire clkos;
    wire clkop;
    wire buf_douto0;

    OB Inst4_OB (.I(buf_clkout), .O(clkout))
             /* synthesis IO_TYPE="LVDS25" */;

    ODDRXE Inst3_ODDRXE0 (.D0(da0), .D1(db0), .SCLK(clkop), .RST(reset), 
        .Q(buf_douto0));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    ODDRXE Inst2_ODDRXE (.D0(scuba_vhi), .D1(scuba_vlo), .SCLK(clkos), .RST(reset), 
        .Q(buf_clkout));

    OB Inst1_OB0 (.I(buf_douto0), .O(dout[0]))
             /* synthesis IO_TYPE="LVDS25" */;

    assign sclk = clkop;
    assign db0 = dataout[1];
    assign da0 = dataout[0];
    assign clkos = clk;
    assign clkop = clk;


    // exemplar begin
    // exemplar attribute Inst4_OB IO_TYPE LVDS25
    // exemplar attribute Inst1_OB0 IO_TYPE LVDS25
    // exemplar end

endmodule
