/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.0.99.2 */
/* Module Version: 5.8 */
/* Fri Jun 02 13:37:24 2017 */

/* parameterized module instance */
DDR_TRANSMIT __ (.clk( ), .clkout( ), .reset( ), .sclk( ), .dataout( ), 
    .dout( ));
