/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.0.99.2 */
/* Module Version: 5.8 */
/* Mon Dec 31 12:53:05 2018 */

/* parameterized module instance */
DDR_RECEIVE __ (.clk( ), .reset( ), .sclk( ), .datain( ), .q( ));
