/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.0.99.2 */
/* Module Version: 6.5 */
/* Fri Jun 02 15:07:01 2017 */

/* parameterized module instance */
DP_RAM1024x8 __ (.WrAddress( ), .RdAddress( ), .Data( ), .WE( ), 
    .RdClock( ), .RdClockEn( ), .Reset( ), .WrClock( ), .WrClockEn( ), 
    .Q( ));
