/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.0.99.2 */
/* Module Version: 5.7 */
/* Thu Jan 17 16:06:03 2019 */

/* parameterized module instance */
PLL_64MHz __ (.CLKI( ), .CLKOP( ));
